/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QxDesktop {
    }
}
declare global {
    interface HTMLQxDesktopElement extends Components.QxDesktop, HTMLStencilElement {
    }
    var HTMLQxDesktopElement: {
        prototype: HTMLQxDesktopElement;
        new (): HTMLQxDesktopElement;
    };
    interface HTMLElementTagNameMap {
        "qx-desktop": HTMLQxDesktopElement;
    }
}
declare namespace LocalJSX {
    interface QxDesktop {
    }
    interface IntrinsicElements {
        "qx-desktop": QxDesktop;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qx-desktop": LocalJSX.QxDesktop & JSXBase.HTMLAttributes<HTMLQxDesktopElement>;
        }
    }
}
